# Generated by Django 5.2.1 on 2025-05-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
